
import React from 'react';

export const content = {
  en: {
    nav: {
      program: 'The Program',
      pricing: 'Pricing',
      contact: 'Contact',
    },
    hero: {
      title: 'Elevate Your Game. Dominate The Ice.',
      subtitle: 'Elite hockey training for dedicated players. Join SniperZone and unlock your potential with our paid monthly subscription.',
      cta: 'Register Now',
    },
    features: {
      title: 'Our Elite Program',
      synthetic: {
        title: 'Synthetic Ice Training',
        description: 'Perfect your shot and stickhandling on our state-of-the-art synthetic ice surfaces during weekday sessions.',
      },
      real: {
        title: 'Real Ice Drills',
        description: 'Apply your skills on real ice every Sunday, focusing on game situations, skating, and team play.',
      },
      pro: {
        title: 'Professional Coaching',
        description: 'Learn from experienced coaches dedicated to player development, providing personalized feedback.',
      },
    },
    pricing: {
      title: 'Join The Elite',
      planName: 'Monthly Subscription',
      price: '$299',
      period: '/month',
      features: [
        'Unlimited Weekday Synthetic Ice Sessions',
        'Guaranteed Sunday Real Ice Slot',
        'Personalized Coaching Feedback',
        'Access to Pro-Level Equipment',
        'Monthly Progress Reports',
      ],
      cta: 'Start My Subscription',
    },
    footer: {
      copy: `© ${new Date().getFullYear()} SniperZone Hockey. All rights reserved.`
    },
    form: {
      title: 'SniperZone Registration',
      steps: {
        step1: 'Player & Parent Info',
        step2: 'Program Selection',
        step3: 'Health & Consents',
        step4: 'Review & Summary',
        step5: 'Payment',
      },
      buttons: {
        back: 'Back',
        next: 'Next',
        proceedToPayment: 'Proceed to Payment',
        pay: 'Pay',
        processing: 'Processing...',
      },
      step1: {
        playerFullName: { label: 'Player Full Name', placeholder: 'Full legal name' },
        dateOfBirth: { label: 'Date of Birth', placeholder: 'YYYY-MM-DD' },
        parentEmail: { label: 'Parent Email', placeholder: 'your@email.com' },
        parentPhone: { label: 'Parent Phone', placeholder: '555-555-5555' },
        emergencyContactName: { label: 'Emergency Contact Name', placeholder: 'Full name' },
        emergencyContactPhone: { label: 'Emergency Contact Phone', placeholder: '555-555-5555' },
        emergencyRelationship: { label: 'Relationship', placeholder: 'e.g., Grandparent, Uncle' },
      },
      step2: {
        title: 'Program Selection',
        programType: { label: 'Select Program Type', placeholder: '-- Choose a Program --' },
        group: 'Group Training',
        private: 'Private Training',
        semiPrivate: 'Semi-Private Training',
        groupDetails: 'Group Training Details',
        privateDetails: 'Private Training Details',
        semiPrivateDetails: 'Semi-Private Training Details',
        frequency: { label: 'Frequency', placeholder: '-- Select Frequency --' },
        selectDay: 'Select Day',
        tuesday: 'Tuesday',
        friday: 'Friday',
        autoScheduled: 'Sessions are automatically scheduled for **Tuesday & Friday**.',
        availableDays: 'Available Days',
        preferredTime: 'Preferred Time Slot',
        oneTime: 'One-time session',
        infoMessage: 'ℹ️ Our team will contact you to match with other players (max 3 per session)',
        availability: 'Availability',
        timeWindows: 'Preferred Time Windows',
        matchingPreference: {
          label: 'Matching Preference',
          sameAge: 'Match with same age group',
          sameLevel: 'Match with same skill level',
          noPreference: 'No preference',
        },
        pricing: 'Pricing:',
      },
      step3: {
        title: 'Health & Consents',
        position: { label: 'Position', placeholder: 'Forward, Defense, Goalie' },
        dominantHand: { label: 'Dominant Hand', left: 'Left', right: 'Right' },
        currentLevel: { label: 'Current Level', placeholder: 'AA, AAA, School, etc.' },
        jerseySize: { label: 'Jersey Size' },
        hasAllergies: 'Has allergies',
        allergiesDetails: { label: 'Allergy Details', placeholder: 'Specify allergies' },
        hasMedicalConditions: 'Has medical conditions',
        medicalConditionsDetails: { label: 'Medical Condition Details', placeholder: 'Specify conditions' },
        medicalReport: { label: 'Medical Report (PDF)', placeholder: 'Upload PDF' },
        photoVideoConsent: 'I consent to photo/video for promotional use',
        policyAcceptance: 'I accept the terms, conditions, and waiver',
      },
      step4: {
        title: 'Review & Payment',
        subtitle: 'Please review all the information carefully before proceeding to payment.',
        summaryTitle: 'Registration Summary',
        pricingTitle: 'Pricing Summary',
        labels: {
          playerName: 'Player Name',
          dateOfBirth: 'Date of Birth',
          parentEmail: 'Parent Email',
          parentPhone: 'Parent Phone',
          emergencyContact: 'Emergency Contact',
          programType: 'Program Type',
          frequency: 'Frequency',
          days: 'Day(s)',
          availableDays: 'Available Days',
          preferredTime: 'Preferred Time',
          availability: 'Availability',
          timeWindows: 'Time Windows',
          matchingPreference: 'Matching Preference',
          jerseySize: 'Jersey Size',
          medicalReport: 'Medical Report',
        },
        billingInterval: {
          monthly: 'Billed monthly (cancel anytime)',
          oneTime: 'One-time payment',
          perSession: 'Pay per session',
        },
      },
      errors: {
        required: 'This field is required.',
        invalidEmail: 'A valid email is required.',
        invalidPhone: 'A valid phone number is required.',
        emergencyPhoneSame: 'Emergency phone must be different from parent phone.',
        selectProgram: 'Please select a program type.',
        selectFrequency: 'Please select a frequency.',
        selectDay: 'Please select a day.',
        selectAtLeastOneDay: 'Please select at least one available day.',
        selectTimeSlot: 'Please select a time slot.',
        selectTimeWindow: 'Please select at least one time window.',
        selectMatching: 'Please select a matching preference.',
        selectJerseySize: 'Please select a jersey size.',
        acceptPolicies: 'You must accept the policies to continue.',
        provideConsent: 'You must provide consent to continue.',
        fileSizeExceeded: 'File size cannot exceed 5MB.',
        invalidFileType: 'Only PDF files are allowed.',
      },
      success: '✅ Registration & Payment Submitted Successfully!\n\nYou will receive a confirmation email shortly.',
      paymentError: 'Payment Error: {error}\n\nPlease check your card details and try again.',
      submissionError: 'Submission failed: {error}\n\nPlease contact support if this persists.',
    },
  },
  fr: {
    nav: {
      program: 'Le Programme',
      pricing: 'Tarifs',
      contact: 'Contact',
    },
    hero: {
      title: 'Élevez Votre Jeu. Dominez La Glace.',
      subtitle: 'Entraînement de hockey élite pour joueurs dédiés. Rejoignez SniperZone et libérez votre potentiel avec notre abonnement mensuel payant.',
      cta: 'Inscrivez-vous maintenant',
    },
    features: {
      title: 'Notre Programme Élite',
      synthetic: {
        title: 'Entraînement sur Glace Synthétique',
        description: 'Perfectionnez votre tir et votre maniement de bâton sur nos surfaces de glace synthétique de pointe durant les sessions de semaine.',
      },
      real: {
        title: 'Exercices sur Vraie Glace',
        description: 'Appliquez vos compétences sur de la vraie glace chaque dimanche, en vous concentrant sur les situations de match, le patinage et le jeu d\'équipe.',
      },
      pro: {
        title: 'Coaching Professionnel',
        description: 'Apprenez de coachs expérimentés dédiés au développement des joueurs, fournissant des retours personnalisés.',
      },
    },
    pricing: {
      title: 'Rejoignez L\'Élite',
      planName: 'Abonnement Mensuel',
      price: '299$',
      period: '/mois',
      features: [
        'Sessions illimitées sur glace synthétique en semaine',
        'Place garantie sur vraie glace le dimanche',
        'Retours personnalisés des coachs',
        'Accès à de l\'équipement de niveau pro',
        'Rapports de progrès mensuels',
      ],
      cta: 'Démarrer Mon Abonnement',
    },
    footer: {
      copy: `© ${new Date().getFullYear()} Hockey SniperZone. Tous droits réservés.`
    },
    form: {
      title: 'Inscription SniperZone',
      steps: {
        step1: 'Info Joueur & Parent',
        step2: 'Sélection du Programme',
        step3: 'Santé & Consentements',
        step4: 'Révision & Sommaire',
        step5: 'Paiement',
      },
      buttons: {
        back: 'Retour',
        next: 'Suivant',
        proceedToPayment: 'Procéder au paiement',
        pay: 'Payer',
        processing: 'Traitement...',
      },
      step1: {
        playerFullName: { label: 'Nom complet du joueur', placeholder: 'Nom légal complet' },
        dateOfBirth: { label: 'Date de naissance', placeholder: 'AAAA-MM-JJ' },
        parentEmail: { label: 'Courriel du parent', placeholder: 'votre@courriel.com' },
        parentPhone: { label: 'Téléphone du parent', placeholder: '555-555-5555' },
        emergencyContactName: { label: 'Nom du contact d\'urgence', placeholder: 'Nom complet' },
        emergencyContactPhone: { label: 'Téléphone du contact d\'urgence', placeholder: '555-555-5555' },
        emergencyRelationship: { label: 'Lien de parenté', placeholder: 'ex: Grand-parent, Oncle' },
      },
      step2: {
        title: 'Sélection du programme',
        programType: { label: 'Sélectionnez le type de programme', placeholder: '-- Choisissez un programme --' },
        group: 'Entraînement de groupe',
        private: 'Entraînement privé',
        semiPrivate: 'Entraînement semi-privé',
        groupDetails: 'Détails de l\'entraînement de groupe',
        privateDetails: 'Détails de l\'entraînement privé',
        semiPrivateDetails: 'Détails de l\'entraînement semi-privé',
        frequency: { label: 'Fréquence', placeholder: '-- Sélectionnez la fréquence --' },
        selectDay: 'Sélectionnez le jour',
        tuesday: 'Mardi',
        friday: 'Vendredi',
        autoScheduled: 'Les sessions sont automatiquement programmées pour **Mardi & Vendredi**.',
        availableDays: 'Jours disponibles',
        preferredTime: 'Plage horaire préférée',
        oneTime: 'Session unique',
        infoMessage: 'ℹ️ Notre équipe vous contactera pour vous jumeler avec d\'autres joueurs (max 3 par session)',
        availability: 'Disponibilité',
        timeWindows: 'Plages horaires préférées',
        matchingPreference: {
          label: 'Préférence de jumelage',
          sameAge: 'Jumeler avec même groupe d\'âge',
          sameLevel: 'Jumeler avec même niveau d\'habileté',
          noPreference: 'Aucune préférence',
        },
        pricing: 'Tarification :',
      },
      step3: {
        title: 'Santé & Consentements',
        position: { label: 'Position', placeholder: 'Avant, Défense, Gardien' },
        dominantHand: { label: 'Main dominante', left: 'Gauche', right: 'Droite' },
        currentLevel: { label: 'Niveau actuel', placeholder: 'AA, AAA, Scolaire, etc.' },
        jerseySize: { label: 'Taille de chandail' },
        hasAllergies: 'A des allergies',
        allergiesDetails: { label: 'Détails des allergies', placeholder: 'Précisez les allergies' },
        hasMedicalConditions: 'A des conditions médicales',
        medicalConditionsDetails: { label: 'Détails des conditions médicales', placeholder: 'Précisez les conditions' },
        medicalReport: { label: 'Rapport médical (PDF)', placeholder: 'Téléverser PDF' },
        photoVideoConsent: 'Je consens à l\'utilisation de photos/vidéos à des fins promotionnelles',
        policyAcceptance: 'J\'accepte les termes, conditions et décharge',
      },
      step4: {
        title: 'Révision & Paiement',
        subtitle: 'Veuillez réviser toutes les informations attentivement avant de procéder au paiement.',
        summaryTitle: 'Sommaire de l\'inscription',
        pricingTitle: 'Sommaire de tarification',
        labels: {
          playerName: 'Nom du joueur',
          dateOfBirth: 'Date de naissance',
          parentEmail: 'Courriel du parent',
          parentPhone: 'Téléphone du parent',
          emergencyContact: 'Contact d\'urgence',
          programType: 'Type de programme',
          frequency: 'Fréquence',
          days: 'Jour(s)',
          availableDays: 'Jours disponibles',
          preferredTime: 'Heure préférée',
          availability: 'Disponibilité',
          timeWindows: 'Plages horaires',
          matchingPreference: 'Préférence de jumelage',
          jerseySize: 'Taille de chandail',
          medicalReport: 'Rapport médical',
        },
        billingInterval: {
          monthly: 'Facturé mensuellement (annulation possible en tout temps)',
          oneTime: 'Paiement unique',
          perSession: 'Paiement par session',
        },
      },
      errors: {
        required: 'Ce champ est requis.',
        invalidEmail: 'Un courriel valide est requis.',
        invalidPhone: 'Un numéro de téléphone valide est requis.',
        emergencyPhoneSame: 'Le téléphone d\'urgence doit être différent du téléphone du parent.',
        selectProgram: 'Veuillez sélectionner un type de programme.',
        selectFrequency: 'Veuillez sélectionner une fréquence.',
        selectDay: 'Veuillez sélectionner un jour.',
        selectAtLeastOneDay: 'Veuillez sélectionner au moins un jour disponible.',
        selectTimeSlot: 'Veuillez sélectionner une plage horaire.',
        selectTimeWindow: 'Veuillez sélectionner au moins une plage horaire.',
        selectMatching: 'Veuillez sélectionner une préférence de jumelage.',
        selectJerseySize: 'Veuillez sélectionner une taille de chandail.',
        acceptPolicies: 'Vous devez accepter les politiques pour continuer.',
        provideConsent: 'Vous devez fournir votre consentement pour continuer.',
        fileSizeExceeded: 'La taille du fichier ne peut excéder 5 Mo.',
        invalidFileType: 'Seuls les fichiers PDF sont acceptés.',
      },
      success: '✅ Inscription & paiement soumis avec succès!\n\nVous recevrez un courriel de confirmation sous peu.',
      paymentError: 'Erreur de paiement : {error}\n\nVeuillez vérifier les détails de votre carte et réessayer.',
      submissionError: 'Échec de soumission : {error}\n\nVeuillez contacter le support si le problème persiste.',
    },
  },
};


export const HockeyPuckIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M12 2C6.48 2 2 3.79 2 6c0 2.21 4.48 4 10 4s10-1.79 10-4c0-2.21-4.48-4-10-4zM2 9v6c0 2.21 4.48 4 10 4s10-1.79 10-4V9c-2.83 1.4-6.31 2-10 2s-7.17-.6-10-2z" />
  </svg>
);

export const IceSkateIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M21.99 15.5c-1.39-1.39-3.26-2.2-5.3-2.34l-1.4-3.88c-.2-.55-.76-.88-1.34-.88H7.09l-.43-1.2c-.2-.56-.76-.88-1.34-.88H2c-.55 0-1 .45-1 1s.45 1 1 1h2.22l2.69 7.48c-.46.33-.87.75-1.22 1.22C4.08 17.92 3 20.06 3 22h2c0-1.69.83-3.23 2.13-4.16l4.63 4.63c.39.39 1.02.39 1.41 0l7.82-7.82c.39-.39.39-1.02 0-1.41l-.26-.26zM15 20c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z" />
  </svg>
);

export const WhistleIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M15.5 14h-.79l-1.21-1.21c.98-1.14 1.5-2.61 1.5-4.29C15 4.48 11.52 1 7.5 1S0 4.48 0 8.5c0 3.53 2.47 6.49 5.75 7.24l.95-.95C4.65 14.1 3 11.5 3 8.5 3 6.02 5.02 4 7.5 4s4.5 2.02 4.5 4.5c0 1.33-.58 2.53-1.5 3.34L9.21 13H3v2h12.5c.67 0 1.28-.28 1.71-.72l3.58-3.58c.78-.78.78-2.05 0-2.83l-2.5-2.5c-.78-.78-2.05-.78-2.83 0l-1.76 1.76c.28.32.53.67.73 1.04l.76-.76c.39-.39 1.02-.39 1.41 0l2.5 2.5c.39.39.39 1.02 0 1.41l-3.58 3.58c-.43.43-1.04.72-1.71.72zM5.13 18.87l-1.26 1.26c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0l1.26-1.26c-.39-.4-.63-.9-.63-1.44 0-.55.24-1.05.63-1.44l-1.41-1.41c-1.56 1.56-1.56 4.09 0 5.65z" />
  </svg>
);
