
import React from 'react';

export const content = {
  en: {
    nav: {
      program: 'The Program',
      pricing: 'Pricing',
      contact: 'Contact',
    },
    hero: {
      title: 'Elevate Your Game. Dominate The Ice.',
      subtitle: 'Elite hockey training for dedicated players. Join SniperZone and unlock your potential with our paid monthly subscription.',
      cta: 'Register Now',
    },
    features: {
      title: 'Our Elite Program',
      synthetic: {
        title: 'Synthetic Ice Training',
        description: 'Perfect your shot and stickhandling on our state-of-the-art synthetic ice surfaces during weekday sessions.',
      },
      real: {
        title: 'Real Ice Drills',
        description: 'Apply your skills on real ice every Sunday, focusing on game situations, skating, and team play.',
      },
      pro: {
        title: 'Professional Coaching',
        description: 'Learn from experienced coaches dedicated to player development, providing personalized feedback.',
      },
    },
    pricing: {
      title: 'Join The Elite',
      planName: 'Monthly Subscription',
      price: '$299',
      period: '/month',
      features: [
        'Unlimited Weekday Synthetic Ice Sessions',
        'Guaranteed Sunday Real Ice Slot',
        'Personalized Coaching Feedback',
        'Access to Pro-Level Equipment',
        'Monthly Progress Reports',
      ],
      cta: 'Start My Subscription',
    },
    footer: {
      copy: `© ${new Date().getFullYear()} SniperZone Hockey. All rights reserved.`
    },
    form: {
      title: 'SniperZone Registration',
      steps: {
        step1: 'Program Selection',
        step2: 'Player & Parent Info',
        step3: 'Health & Consents',
        step4: 'Review & Summary',
        step5: 'Payment',
      },
      buttons: {
        back: 'Back',
        next: 'Next',
        proceedToPayment: 'Proceed to Payment',
        pay: 'Pay',
        processing: 'Processing...',
      },
      step1: {
        title: 'Player & Parent Info',
        playerInfoHeader: 'Player Information',
        parentInfoHeader: 'Parent / Guardian Information',
        emergencyContactHeader: 'Emergency Contact',
        playerFullName: { label: 'Player Full Name', placeholder: 'Full legal name' },
        dateOfBirth: { label: 'Date of Birth', placeholder: 'YYYY-MM-DD' },
        playerCategory: { label: 'Player Category', placeholder: '-- Select Category --' },
        parentFullName: { label: 'Parent/Guardian Full Name', placeholder: 'Full legal name' },
        parentEmail: { label: 'Parent Email', placeholder: 'your@email.com' },
        parentPhone: { label: 'Parent Phone', placeholder: '555-555-5555' },
        parentCity: { label: 'City', placeholder: 'City name' },
        parentPostalCode: { label: 'Postal Code', placeholder: 'A1A 1A1' },
        communicationLanguage: { label: 'Preferred Communication Language', placeholder: '-- Select Language --' },
        emergencyContactName: { label: 'Contact Full Name', placeholder: 'Full name' },
        emergencyContactPhone: { label: 'Contact Phone', placeholder: '555-555-5555' },
        emergencyRelationship: { label: 'Relationship to Player', placeholder: 'e.g., Grandparent, Uncle' },
      },
      step2: {
        title: 'Program Selection',
        programType: { label: 'Select Program Type', placeholder: '-- Choose a Program --' },
        group: 'Group Training',
        private: 'Private Training',
        semiPrivate: 'Semi-Private Training',
        groupDetails: 'Group Training Details',
        privateDetails: 'Private Training Details',
        semiPrivateDetails: 'Semi-Private Training Details',
        frequency: { label: 'Frequency', placeholder: '-- Select Frequency --' },
        selectDay: 'Select Day',
        tuesday: 'Tuesday',
        friday: 'Friday',
        autoScheduled: 'Sessions are automatically scheduled for **Tuesday & Friday**.',
        availableDays: 'Available Days',
        preferredTime: 'Preferred Time Slot',
        oneTime: 'One-time session',
        infoMessage: 'ℹ️ Our team will contact you to match with other players (max 3 per session)',
        availability: 'Availability',
        timeWindows: 'Preferred Time Windows',
        matchingPreference: {
          label: 'Matching Preference',
          sameAge: 'Match with same age group',
          sameLevel: 'Match with same skill level',
          noPreference: 'No preference',
        },
        pricing: 'Pricing:',
        assignedTimeSlot: 'Assigned Time Slot:',
        basedOnCategory: 'Based on your player category',
        checkingAvailability: 'Checking availability...',
        slotFull: 'This time slot is FULL',
        spotsRemaining: 'spot(s) remaining!',
        spotsAvailable: 'spot(s) available',
        onlySpots: 'Only',
        registrationUnavailable: 'Registration Unavailable',
        capacityMessage: 'This time slot is currently at full capacity. Please contact us at info@sniperzone.com to join the waitlist.',
        sundayPracticeLabel: 'I agree to participate in Sunday practices (once per month, 11:00 AM - 12:30 PM)',
        sundayPracticeNote: 'Note: Sunday practices are mandatory for Group Training participants and occur once monthly on real ice.',
        sessionFrequency: 'Session Frequency',
        preferredDays: 'Preferred Days',
        selectAllDays: 'Select all days you\'re available for private sessions',
        timeSlotPlaceholder: '-- Select Time Slot --',
        morningSlot: 'Morning (8 AM - 12 PM)',
        afternoonSlot: 'Early Afternoon (12 PM - 3 PM)',
        eveningSlot: 'Evening (Group Training - Not available for Private/Semi-Private)',
        contactMessage: '📞 Our team will contact you within 24 hours to schedule your private training sessions based on your preferences.',
        selectAllAvailable: 'Select all days you\'re available (we\'ll match you with players with similar availability)',
        matchingPreferencePlaceholder: '-- Select Preference --',
        sameLevel: 'Same skill level',
        flexible: 'Flexible - any skill level',
        higherLevel: 'Train with higher skill level',
        howSemiPrivateWorks: '🤝 How Semi-Private Works',
        semiPrivatePoint1: 'We\'ll match you with 1-2 other players of similar age and skill level',
        semiPrivatePoint2: 'Our intelligent matching system finds the best compatibility based on your preferences',
        semiPrivatePoint3: 'More affordable than private training while maintaining personalized attention',
        semiPrivatePoint4: 'You\'ll be notified within 48 hours when a compatible group is formed',
      },
      step3: {
        title: 'Health & Consents',
        hockeyInfoHeader: 'Hockey Information',
        healthMedicalHeader: 'Health & Medical',
        consentsHeader: 'Consents',
        position: { label: 'Position', placeholder: 'Forward, Defense, Goalie' },
        dominantHand: { label: 'Dominant Hand', selectHand: '-- Select Hand --', left: 'Left', right: 'Right' },
        currentLevel: { label: 'Current Level (e.g., AA, AAA)', placeholder: 'AA, AAA, School, etc.' },
        jerseySize: { label: 'Jersey Size', selectSize: '-- Select Size --' },
        primaryObjective: { label: 'Primary Training Objective', placeholder: '-- Select Objective --' },
        shooting: 'Shooting',
        puckHandling: 'Puck Handling',
        skating: 'Skating',
        endurance: 'Endurance',
        hasAllergies: 'Player has allergies',
        allergiesDetails: { label: 'Please provide details', placeholder: 'Specify allergies' },
        hasMedicalConditions: 'Player has existing medical conditions',
        medicalConditionsDetails: { label: 'Please provide details', placeholder: 'Specify conditions' },
        carriesMedication: 'Player carries medication (EpiPen, inhaler, etc.)',
        medicationDetails: { label: 'Medication Details', placeholder: 'Specify medication details' },
        medicationActionPlan: { label: 'Upload Action Plan (PDF, max 5MB)', helpText: 'Please upload your emergency action plan for medication administration' },
        medicalReport: { label: 'Upload Medical Report (Optional, PDF only, max 5MB)', placeholder: 'Upload PDF' },
        photoVideoConsent: 'I consent to the use of photos and videos of the player for promotional purposes.',
        policyAcceptance: 'I have read and agree to the',
        termsLink: 'Terms of Service and Waiver',
      },
      step4: {
        title: 'Review & Payment',
        reviewTitle: 'Review Your Information',
        subtitle: 'Please review all the information carefully before submitting your registration.',
        summaryTitle: 'Registration Summary',
        pricingTitle: 'Pricing Summary',
        labels: {
          playerName: 'Player Name',
          dateOfBirth: 'Date of Birth',
          parentEmail: 'Parent Email',
          parentPhone: 'Parent Phone',
          emergencyContact: 'Emergency Contact',
          programType: 'Program Type',
          frequency: 'Frequency',
          groupFrequency: 'Group Frequency',
          groupDays: 'Group Day(s)',
          days: 'Day(s)',
          availableDays: 'Available Days',
          preferredTime: 'Preferred Time',
          availability: 'Availability',
          timeWindows: 'Time Windows',
          matchingPreference: 'Matching Preference',
          jerseySize: 'Jersey Size',
          medicalReport: 'Medical Report',
          consents: 'Consents',
          consentsAgreed: 'Photo/Video & Policies Agreed',
          tuesdayFriday: 'Tuesday & Friday',
        },
        billingInterval: {
          monthly: 'Billed monthly (cancel anytime)',
          oneTime: 'One-time payment',
          perSession: 'Pay per session',
        },
      },
      errors: {
        required: 'This field is required.',
        invalidEmail: 'A valid email is required.',
        invalidPhone: 'A valid phone number is required.',
        emergencyPhoneSame: 'Emergency phone must be different from parent phone.',
        selectProgram: 'Please select a program type.',
        selectFrequency: 'Please select a frequency.',
        selectDay: 'Please select a day.',
        selectAtLeastOneDay: 'Please select at least one available day.',
        selectTimeSlot: 'Please select a time slot.',
        selectTimeWindow: 'Please select at least one time window.',
        selectMatching: 'Please select a matching preference.',
        selectJerseySize: 'Please select a jersey size.',
        acceptPolicies: 'You must accept the policies to continue.',
        provideConsent: 'You must provide consent to continue.',
        fileSizeExceeded: 'File size cannot exceed 5MB.',
        invalidFileType: 'Only PDF files are allowed.',
      },
      success: '✅ Registration & Payment Submitted Successfully!\n\nYou will receive a confirmation email shortly.',
      paymentError: 'Payment Error: {error}\n\nPlease check your card details and try again.',
      paymentFailedButRegistered: 'Registration created but payment failed: {error}. Please contact support to complete payment.',
      submissionError: 'Submission failed: {error}\n\nPlease contact support if this persists.',
    },
  },
  fr: {
    nav: {
      program: 'Le Programme',
      pricing: 'Tarifs',
      contact: 'Contact',
    },
    hero: {
      title: 'Élevez Votre Jeu. Dominez La Glace.',
      subtitle: 'Entraînement de hockey élite pour joueurs dédiés. Rejoignez SniperZone et libérez votre potentiel avec notre abonnement mensuel payant.',
      cta: 'Inscrivez-vous maintenant',
    },
    features: {
      title: 'Notre Programme Élite',
      synthetic: {
        title: 'Entraînement sur Glace Synthétique',
        description: 'Perfectionnez votre tir et votre maniement de bâton sur nos surfaces de glace synthétique de pointe durant les sessions de semaine.',
      },
      real: {
        title: 'Exercices sur Vraie Glace',
        description: 'Appliquez vos compétences sur de la vraie glace chaque dimanche, en vous concentrant sur les situations de match, le patinage et le jeu d\'équipe.',
      },
      pro: {
        title: 'Coaching Professionnel',
        description: 'Apprenez de coachs expérimentés dédiés au développement des joueurs, fournissant des retours personnalisés.',
      },
    },
    pricing: {
      title: 'Rejoignez L\'Élite',
      planName: 'Abonnement Mensuel',
      price: '299$',
      period: '/mois',
      features: [
        'Sessions illimitées sur glace synthétique en semaine',
        'Place garantie sur vraie glace le dimanche',
        'Retours personnalisés des coachs',
        'Accès à de l\'équipement de niveau pro',
        'Rapports de progrès mensuels',
      ],
      cta: 'Démarrer Mon Abonnement',
    },
    footer: {
      copy: `© ${new Date().getFullYear()} Hockey SniperZone. Tous droits réservés.`
    },
    form: {
      title: 'Inscription SniperZone',
      steps: {
        step1: 'Sélection du Programme',
        step2: 'Info Joueur & Parent',
        step3: 'Santé & Consentements',
        step4: 'Révision & Sommaire',
        step5: 'Paiement',
      },
      buttons: {
        back: 'Retour',
        next: 'Suivant',
        proceedToPayment: 'Procéder au paiement',
        pay: 'Payer',
        processing: 'Traitement...',
      },
      step1: {
        title: 'Info Joueur & Parent',
        playerInfoHeader: 'Informations du joueur',
        parentInfoHeader: 'Informations du parent / tuteur',
        emergencyContactHeader: 'Contact d\'urgence',
        playerFullName: { label: 'Nom complet du joueur', placeholder: 'Nom légal complet' },
        dateOfBirth: { label: 'Date de naissance', placeholder: 'AAAA-MM-JJ' },
        playerCategory: { label: 'Catégorie du joueur', placeholder: '-- Sélectionnez catégorie --' },
        parentFullName: { label: 'Nom complet du parent/tuteur', placeholder: 'Nom légal complet' },
        parentEmail: { label: 'Courriel du parent', placeholder: 'votre@courriel.com' },
        parentPhone: { label: 'Téléphone du parent', placeholder: '555-555-5555' },
        parentCity: { label: 'Ville', placeholder: 'Nom de la ville' },
        parentPostalCode: { label: 'Code postal', placeholder: 'A1A 1A1' },
        communicationLanguage: { label: 'Langue de communication préférée', placeholder: '-- Sélectionnez langue --' },
        emergencyContactName: { label: 'Nom complet du contact', placeholder: 'Nom complet' },
        emergencyContactPhone: { label: 'Téléphone du contact', placeholder: '555-555-5555' },
        emergencyRelationship: { label: 'Lien avec le joueur', placeholder: 'ex: Grand-parent, Oncle' },
      },
      step2: {
        title: 'Sélection du programme',
        programType: { label: 'Sélectionnez le type de programme', placeholder: '-- Choisissez un programme --' },
        group: 'Entraînement de groupe',
        private: 'Entraînement privé',
        semiPrivate: 'Entraînement semi-privé',
        groupDetails: 'Détails de l\'entraînement de groupe',
        privateDetails: 'Détails de l\'entraînement privé',
        semiPrivateDetails: 'Détails de l\'entraînement semi-privé',
        frequency: { label: 'Fréquence', placeholder: '-- Sélectionnez la fréquence --' },
        selectDay: 'Sélectionnez le jour',
        tuesday: 'Mardi',
        friday: 'Vendredi',
        autoScheduled: 'Les sessions sont automatiquement programmées pour **Mardi & Vendredi**.',
        availableDays: 'Jours disponibles',
        preferredTime: 'Plage horaire préférée',
        oneTime: 'Session unique',
        infoMessage: 'ℹ️ Notre équipe vous contactera pour vous jumeler avec d\'autres joueurs (max 3 par session)',
        availability: 'Disponibilité',
        timeWindows: 'Plages horaires préférées',
        matchingPreference: {
          label: 'Préférence de jumelage',
          sameAge: 'Jumeler avec même groupe d\'âge',
          sameLevel: 'Jumeler avec même niveau d\'habileté',
          noPreference: 'Aucune préférence',
        },
        pricing: 'Tarification :',
        assignedTimeSlot: 'Plage horaire assignée :',
        basedOnCategory: 'Basée sur votre catégorie de joueur',
        checkingAvailability: 'Vérification de la disponibilité...',
        slotFull: 'Cette plage horaire est COMPLÈTE',
        spotsRemaining: 'place(s) restante(s)!',
        spotsAvailable: 'place(s) disponible(s)',
        onlySpots: 'Seulement',
        registrationUnavailable: 'Inscription non disponible',
        capacityMessage: 'Cette plage horaire est actuellement à pleine capacité. Veuillez nous contacter à info@sniperzone.com pour rejoindre la liste d\'attente.',
        sundayPracticeLabel: 'J\'accepte de participer aux pratiques du dimanche (une fois par mois, 11h00 - 12h30)',
        sundayPracticeNote: 'Note : Les pratiques du dimanche sont obligatoires pour les participants à l\'entraînement de groupe et ont lieu une fois par mois sur vraie glace.',
        sessionFrequency: 'Fréquence des sessions',
        preferredDays: 'Jours préférés',
        selectAllDays: 'Sélectionnez tous les jours où vous êtes disponible pour les sessions privées',
        timeSlotPlaceholder: '-- Sélectionnez une plage horaire --',
        morningSlot: 'Matin (8h - 12h)',
        afternoonSlot: 'Début d\'après-midi (12h - 15h)',
        eveningSlot: 'Soir (Entraînement de groupe - Non disponible pour Privé/Semi-Privé)',
        contactMessage: '📞 Notre équipe vous contactera dans les 24 heures pour planifier vos sessions d\'entraînement privé selon vos préférences.',
        selectAllAvailable: 'Sélectionnez tous les jours où vous êtes disponible (nous vous jumèlerons avec des joueurs ayant une disponibilité similaire)',
        matchingPreferencePlaceholder: '-- Sélectionnez une préférence --',
        sameLevel: 'Même niveau d\'habileté',
        flexible: 'Flexible - tous niveaux',
        higherLevel: 'S\'entraîner avec un niveau supérieur',
        howSemiPrivateWorks: '🤝 Comment fonctionne le semi-privé',
        semiPrivatePoint1: 'Nous vous jumèlerons avec 1-2 autres joueurs d\'âge et de niveau similaires',
        semiPrivatePoint2: 'Notre système de jumelage intelligent trouve la meilleure compatibilité selon vos préférences',
        semiPrivatePoint3: 'Plus abordable que l\'entraînement privé tout en maintenant une attention personnalisée',
        semiPrivatePoint4: 'Vous serez notifié dans les 48 heures lorsqu\'un groupe compatible sera formé',
      },
      step3: {
        title: 'Santé & Consentements',
        hockeyInfoHeader: 'Informations hockey',
        healthMedicalHeader: 'Santé & Médical',
        consentsHeader: 'Consentements',
        position: { label: 'Position', placeholder: 'Avant, Défense, Gardien' },
        dominantHand: { label: 'Main dominante', selectHand: '-- Sélectionnez la main --', left: 'Gauche', right: 'Droite' },
        currentLevel: { label: 'Niveau actuel (ex: AA, AAA)', placeholder: 'AA, AAA, Scolaire, etc.' },
        jerseySize: { label: 'Taille de chandail', selectSize: '-- Sélectionnez la taille --' },
        primaryObjective: { label: 'Objectif principal d\'entraînement', placeholder: '-- Sélectionnez l\'objectif --' },
        shooting: 'Tir',
        puckHandling: 'Maniement de rondelle',
        skating: 'Patinage',
        endurance: 'Endurance',
        hasAllergies: 'Le joueur a des allergies',
        allergiesDetails: { label: 'Veuillez fournir les détails', placeholder: 'Précisez les allergies' },
        hasMedicalConditions: 'Le joueur a des conditions médicales existantes',
        medicalConditionsDetails: { label: 'Veuillez fournir les détails', placeholder: 'Précisez les conditions' },
        carriesMedication: 'Le joueur transporte des médicaments (EpiPen, inhalateur, etc.)',
        medicationDetails: { label: 'Détails des médicaments', placeholder: 'Précisez les détails des médicaments' },
        medicationActionPlan: { label: 'Téléverser le plan d\'action (PDF, max 5 Mo)', helpText: 'Veuillez téléverser votre plan d\'action d\'urgence pour l\'administration de médicaments' },
        medicalReport: { label: 'Téléverser le rapport médical (Optionnel, PDF uniquement, max 5 Mo)', placeholder: 'Téléverser PDF' },
        photoVideoConsent: 'Je consens à l\'utilisation de photos et vidéos du joueur à des fins promotionnelles.',
        policyAcceptance: 'J\'ai lu et j\'accepte les',
        termsLink: 'Conditions de service et Décharge',
      },
      step4: {
        title: 'Révision & Paiement',
        reviewTitle: 'Réviser vos informations',
        subtitle: 'Veuillez réviser toutes les informations attentivement avant de soumettre votre inscription.',
        summaryTitle: 'Sommaire de l\'inscription',
        pricingTitle: 'Sommaire de tarification',
        labels: {
          playerName: 'Nom du joueur',
          dateOfBirth: 'Date de naissance',
          parentEmail: 'Courriel du parent',
          parentPhone: 'Téléphone du parent',
          emergencyContact: 'Contact d\'urgence',
          programType: 'Type de programme',
          frequency: 'Fréquence',
          groupFrequency: 'Fréquence de groupe',
          groupDays: 'Jour(s) de groupe',
          days: 'Jour(s)',
          availableDays: 'Jours disponibles',
          preferredTime: 'Heure préférée',
          availability: 'Disponibilité',
          timeWindows: 'Plages horaires',
          matchingPreference: 'Préférence de jumelage',
          jerseySize: 'Taille de chandail',
          medicalReport: 'Rapport médical',
          consents: 'Consentements',
          consentsAgreed: 'Photo/Vidéo & Politiques acceptées',
          tuesdayFriday: 'Mardi & Vendredi',
        },
        billingInterval: {
          monthly: 'Facturé mensuellement (annulation possible en tout temps)',
          oneTime: 'Paiement unique',
          perSession: 'Paiement par session',
        },
      },
      errors: {
        required: 'Ce champ est requis.',
        invalidEmail: 'Un courriel valide est requis.',
        invalidPhone: 'Un numéro de téléphone valide est requis.',
        emergencyPhoneSame: 'Le téléphone d\'urgence doit être différent du téléphone du parent.',
        selectProgram: 'Veuillez sélectionner un type de programme.',
        selectFrequency: 'Veuillez sélectionner une fréquence.',
        selectDay: 'Veuillez sélectionner un jour.',
        selectAtLeastOneDay: 'Veuillez sélectionner au moins un jour disponible.',
        selectTimeSlot: 'Veuillez sélectionner une plage horaire.',
        selectTimeWindow: 'Veuillez sélectionner au moins une plage horaire.',
        selectMatching: 'Veuillez sélectionner une préférence de jumelage.',
        selectJerseySize: 'Veuillez sélectionner une taille de chandail.',
        acceptPolicies: 'Vous devez accepter les politiques pour continuer.',
        provideConsent: 'Vous devez fournir votre consentement pour continuer.',
        fileSizeExceeded: 'La taille du fichier ne peut excéder 5 Mo.',
        invalidFileType: 'Seuls les fichiers PDF sont acceptés.',
      },
      success: '✅ Inscription & paiement soumis avec succès!\n\nVous recevrez un courriel de confirmation sous peu.',
      paymentError: 'Erreur de paiement : {error}\n\nVeuillez vérifier les détails de votre carte et réessayer.',
      paymentFailedButRegistered: 'Inscription créée mais le paiement a échoué : {error}. Veuillez contacter le support pour compléter le paiement.',
      submissionError: 'Échec de soumission : {error}\n\nVeuillez contacter le support si le problème persiste.',
    },
  },
};


export const HockeyPuckIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M12 2C6.48 2 2 3.79 2 6c0 2.21 4.48 4 10 4s10-1.79 10-4c0-2.21-4.48-4-10-4zM2 9v6c0 2.21 4.48 4 10 4s10-1.79 10-4V9c-2.83 1.4-6.31 2-10 2s-7.17-.6-10-2z" />
  </svg>
);

export const IceSkateIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M21.99 15.5c-1.39-1.39-3.26-2.2-5.3-2.34l-1.4-3.88c-.2-.55-.76-.88-1.34-.88H7.09l-.43-1.2c-.2-.56-.76-.88-1.34-.88H2c-.55 0-1 .45-1 1s.45 1 1 1h2.22l2.69 7.48c-.46.33-.87.75-1.22 1.22C4.08 17.92 3 20.06 3 22h2c0-1.69.83-3.23 2.13-4.16l4.63 4.63c.39.39 1.02.39 1.41 0l7.82-7.82c.39-.39.39-1.02 0-1.41l-.26-.26zM15 20c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z" />
  </svg>
);

export const WhistleIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M15.5 14h-.79l-1.21-1.21c.98-1.14 1.5-2.61 1.5-4.29C15 4.48 11.52 1 7.5 1S0 4.48 0 8.5c0 3.53 2.47 6.49 5.75 7.24l.95-.95C4.65 14.1 3 11.5 3 8.5 3 6.02 5.02 4 7.5 4s4.5 2.02 4.5 4.5c0 1.33-.58 2.53-1.5 3.34L9.21 13H3v2h12.5c.67 0 1.28-.28 1.71-.72l3.58-3.58c.78-.78.78-2.05 0-2.83l-2.5-2.5c-.78-.78-2.05-.78-2.83 0l-1.76 1.76c.28.32.53.67.73 1.04l.76-.76c.39-.39 1.02-.39 1.41 0l2.5 2.5c.39.39.39 1.02 0 1.41l-3.58 3.58c-.43.43-1.04.72-1.71.72zM5.13 18.87l-1.26 1.26c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0l1.26-1.26c-.39-.4-.63-.9-.63-1.44 0-.55.24-1.05.63-1.44l-1.41-1.41c-1.56 1.56-1.56 4.09 0 5.65z" />
  </svg>
);
